# Blobnom Cluster Node 1 Configuration

# Basic server configuration
data_dir = "data"
num_shards = 4
storage_compression = true
output_compression = false
async_write = true
batch_size = 100
batch_timeout_ms = 10
addr = "0.0.0.0:6381"

# Cluster configuration
[cluster]
# Enable cluster mode
enabled = true

# Unique node identifier for this node
node_id = "node-1"

# List of seed nodes to connect to when joining the cluster
# These are the gossip addresses of the other nodes (internal Docker network)
seeds = ["127.0.0.1:7002", "127.0.0.1:7003"]

# Address that other nodes should use to connect to this node
# For Docker, this should be the internal container hostname
advertise_addr = "127.0.0.1:7001"

# Port for gossip protocol communication
port = 7001

# Hash slot ranges for this node (0-5460)
[[cluster.slot_ranges]]
start = 0
end = 5460

# Gossip interval in milliseconds
gossip_interval_ms = 1000
