# Blobnom Cluster Node 3 Configuration

# Basic server configuration
data_dir = "/app/data"
num_shards = 4
async_write = true
batch_size = 100
batch_timeout_ms = 10
addr = "0.0.0.0:6383"

# Storage compression
[storage_compression]
enabled = true
algorithm = "zstd" # Options: gzip, zstd, lz4, brotli
level = 3

# Cluster configuration
[cluster]
# Enable cluster mode
enabled = true

# Unique node identifier for this node
node_id = "node-3"

# List of seed nodes to connect to when joining the cluster
# These are the gossip addresses of the other nodes (internal Docker network)
seeds = ["127.0.0.1:7001", "127.0.0.1:7002"]

# Address that other nodes should use to connect to this node
# For Docker, this should be the internal container hostname
advertise_addr = "127.0.0.1:7003"

# Port for gossip protocol communication
port = 7003

# Hash slot ranges for this node (10923-16383)
[[cluster.slot_ranges]]
start = 10923
end = 16383

# Gossip interval in milliseconds
gossip_interval_ms = 1000
