services:
  node1:
    image: rust:1.87
    container_name: blobnom-node1
    hostname: node1
    ports:
      - "6381:6379"
      - "7001:7000"
    volumes:
      - ../:/workspace
      - ./config.node1.toml:/app/config.toml:ro
      - node1_data:/app/data
      - cargo_cache:/usr/local/cargo/registry
    networks:
      - blobnom-cluster
    working_dir: /workspace
    command: >
      bash -c "
        echo 'Checking binary compatibility...';
        if [ ! -f target/release/blobnom ] || ! file target/release/blobnom | grep -q 'ELF 64-bit LSB pie executable, x86-64'; then
          echo 'Building blobnom for container architecture...';
          cargo build --release;
        else
          echo 'Using existing compatible binary...';
        fi;
        mkdir -p /app/data;
        exec ./target/release/blobnom --config /app/config.toml
      "

  node2:
    image: rust:1.87
    container_name: blobnom-node2
    hostname: node2
    ports:
      - "6382:6379"
      - "7002:7000"
    volumes:
      - ../:/workspace
      - ./config.node2.toml:/app/config.toml:ro
      - node2_data:/app/data
      - cargo_cache:/usr/local/cargo/registry
    networks:
      - blobnom-cluster
    working_dir: /workspace
    command: >
      bash -c "
        echo 'Checking binary compatibility...';
        if [ ! -f target/release/blobnom ] || ! file target/release/blobnom | grep -q 'ELF 64-bit LSB pie executable, x86-64'; then
          echo 'Building blobnom for container architecture...';
          cargo build --release;
        else
          echo 'Using existing compatible binary...';
        fi;
        mkdir -p /app/data;
        exec ./target/release/blobnom --config /app/config.toml
      "

  node3:
    image: rust:1.87
    container_name: blobnom-node3
    hostname: node3
    ports:
      - "6383:6379"
      - "7003:7000"
    volumes:
      - ../:/workspace
      - ./config.node3.toml:/app/config.toml:ro
      - node3_data:/app/data
      - cargo_cache:/usr/local/cargo/registry
    networks:
      - blobnom-cluster
    working_dir: /workspace
    command: >
      bash -c "
        echo 'Checking binary compatibility...';
        if [ ! -f target/release/blobnom ] || ! file target/release/blobnom | grep -q 'ELF 64-bit LSB pie executable, x86-64'; then
          echo 'Building blobnom for container architecture...';
          cargo build --release;
        else
          echo 'Using existing compatible binary...';
        fi;
        mkdir -p /app/data;
        exec ./target/release/blobnom --config /app/config.toml
      "

networks:
  blobnom-cluster:
    driver: bridge

volumes:
  node1_data:
  node2_data:
  node3_data:
  cargo_cache:
